import type { Context } from '@deepseek-ai/cordis';
import type { TuiStartupOptions } from './startup.js';
import { DeepSeekTui } from './ui.js';
export declare const name = "dsh-tui-runner";
export declare const inject: string[];
export declare class DshTuiRunner {
    private readonly ctx;
    private readonly startup;
    private readonly ui;
    private handle?;
    private selection?;
    private readonly subscriptions;
    private readonly interactionDisposers;
    private busyEnter;
    private projection?;
    private projectionCursor;
    private closing;
    private started;
    constructor(ctx: Context, startup: TuiStartupOptions, ui?: DeepSeekTui);
    private get agent();
    start(): Promise<void>;
    private installInteractions;
    private askApproval;
    private askQuestions;
    private open;
    private bindAgent;
    private refreshSlashCommands;
    private refresh;
    submit(raw: string): Promise<void>;
    private runHarnessCommand;
    interrupt(): void;
    private switchSession;
    private detachCurrent;
    private showSessions;
    private chooseSession;
    private loadSessionPickerItems;
    private permissionPickerItems;
    private choosePermission;
    private chooseGoalCommand;
    private choosePlanCommand;
    private loadModels;
    private showModels;
    private selectModel;
    private loadReasoningPickerItems;
    private chooseReasoning;
    private selectReasoning;
    private selectBusyEnter;
    private settingsSummary;
    private loadSettingsNamespacePickerItems;
    private editAdvancedSettings;
    private settingsChoices;
    private chooseSettings;
    private applySetting;
    private pauseAndExit;
    shutdown(requestExit: boolean, stopUi?: boolean): Promise<void>;
}
export declare function apply(ctx: Context): void;
export { DeepSeekTui } from './ui.js';
export { projectSession } from './projection.js';
