import type { Context } from '@deepseek-ai/cordis';
import type { SettingsScope } from '@deepseek-ai/dsh-settings';
import type { TuiStartupOptions } from './startup.js';
import { type TranscriptSettings } from './transcript-settings.js';
import { DeepSeekTui } from './ui.js';
export declare const name = "dsh-tui-runner";
export declare const inject: string[];
export declare class DshTuiRunner {
    private readonly ctx;
    private readonly startup;
    private readonly ui;
    private readonly transcriptSettings?;
    private handle?;
    private selection?;
    private readonly subscriptions;
    private readonly interactionDisposers;
    private busyEnter;
    private projection?;
    private projectionCursor;
    private closing;
    private started;
    private localTranscriptDensity;
    private selectedContextWindow?;
    private shortcutQueue;
    private actionQueue;
    private sessionGeneration;
    private sessionLoadAbort?;
    private readonly sessionNavigatorCache;
    constructor(ctx: Context, startup: TuiStartupOptions, ui?: DeepSeekTui, transcriptSettings?: SettingsScope<TranscriptSettings> | undefined);
    private get transcriptDensity();
    private get agent();
    start(): Promise<void>;
    private installInteractions;
    private askApproval;
    private askQuestions;
    private prepareSession;
    private activateSession;
    private open;
    private bindAgent;
    private refreshSlashCommands;
    private refresh;
    private resolveContextWindow;
    private enqueueShortcut;
    private enqueueAction;
    private togglePlanMode;
    private stepReasoning;
    submit(raw: string): Promise<void>;
    private processSubmission;
    private runHarnessCommand;
    interrupt(): void;
    private pendingInboxCount;
    private blockSessionChangeForPending;
    private requestSessionSwitch;
    private switchSession;
    private detachCurrent;
    private chooseSession;
    private loadSessionPickerItems;
    private loadSessionPickerSource;
    private liveSessionPickerSource;
    private sessionPickerSource;
    private permissionPickerItems;
    private choosePermission;
    private chooseGoalCommand;
    private choosePlanCommand;
    private loadModels;
    private showModels;
    private selectModel;
    private loadReasoningPickerItems;
    private chooseReasoning;
    private selectReasoning;
    private selectBusyEnter;
    private settingsSummary;
    private loadSettingsNamespacePickerItems;
    private editAdvancedSettings;
    private settingsChoices;
    private chooseSettings;
    private applySetting;
    private selectTranscriptDensity;
    private pauseAndExit;
    shutdown(requestExit: boolean, stopUi?: boolean): Promise<void>;
}
export declare function apply(ctx: Context): void;
export { DeepSeekTui } from './ui.js';
export { projectSession } from './projection.js';
export { DEFAULT_TRANSCRIPT_DENSITY, TRANSCRIPT_DENSITIES, TRANSCRIPT_DENSITY_PICKER_ITEMS, TRANSCRIPT_SETTINGS_NAMESPACE, TRANSCRIPT_SETTINGS_SCHEMA, type TranscriptDensity, type TranscriptSettings, } from './transcript-settings.js';
