import type { Context } from '@deepseek-ai/cordis';
import type { Agent, ModelSelectionRef } from '@deepseek-ai/dsh-agent';
import { type LlmResolvedModelInfo } from '@deepseek-ai/dsh-llm';
import type { SettingsScope } from '@deepseek-ai/dsh-settings';
import { type ModelPickerSource, type PickerItem } from './interaction.js';
import { type TranscriptDensity, type TranscriptSettings } from './transcript-settings.js';
import type { DeepSeekTui } from './ui.js';
type BusyEnter = 'queue' | 'steer';
export interface SettingsControllerDependencies {
    ctx: Context;
    ui: DeepSeekTui;
    transcriptSettings?: SettingsScope<TranscriptSettings>;
    startupCwd?: string;
    getAgent(): Agent;
    getSelection(): ModelSelectionRef | undefined;
    setSelectedContextWindow(value: number | undefined): void;
    runHarnessCommand(line: string): Promise<void>;
    refresh(): void;
    isClosing(): boolean;
    hasPendingImages(): boolean;
}
export declare const SETTINGS_PICKER_ITEMS: readonly PickerItem[];
export declare function assertModelSupportsSessionImages(agent: Agent, info: LlmResolvedModelInfo, hasPendingImages?: boolean): void;
export declare class SettingsController {
    readonly deps: SettingsControllerDependencies;
    private localTranscriptDensity;
    private readonly disposers;
    busyEnter: BusyEnter;
    constructor(deps: SettingsControllerDependencies);
    dispose(): void;
    get transcriptDensity(): TranscriptDensity;
    settingPickerItems(): PickerItem[];
    settingCompletions(prefix: string): PickerItem[];
    modelCompletions(prefix: string): Promise<PickerItem[]>;
    busyCompletions(prefix: string): PickerItem[];
    permissionPickerItems(): PickerItem[];
    choosePermission(): Promise<void>;
    loadModels(): Promise<ModelPickerSource[]>;
    showModels(): Promise<void>;
    selectModel(value: string): Promise<void>;
    loadReasoningPickerItems(): Promise<PickerItem[]>;
    selectReasoning(value: string): Promise<void>;
    selectBusyEnter(value: string): Promise<void>;
    chooseSettings(action?: string): Promise<void>;
    selectTranscriptDensity(): Promise<void>;
    private settingsChoices;
    private applySetting;
    currentModelLabel(): string;
    currentReasoningLabel(): string;
    currentPermission(): string;
    defaultModelLabel(): string;
    showSummary(): void;
    saveModelDefault(): Promise<void>;
    savePermissionDefault(): Promise<void>;
    showProviders(): Promise<void>;
    showRuntime(): void;
    showSupport(): Promise<void>;
    settingsNamespaceCount(): number;
    private loadSettingsNamespacePickerItems;
    editAdvancedSettings(namespace?: string): Promise<void>;
}
export {};
